from __future__ import annotations


def _candles(*items: tuple[str, int]) -> list[dict[str, int | str]]:
    return [
        {
            "interval": interval,
            "retention_bars": max(retention_bars, 20160) if interval == "15m" else retention_bars,
        }
        for interval, retention_bars in items
    ]


WATCHED_ASSETS: list[dict[str, object]] = [
    {
        "symbol": "BTCUSD",
        "name": "Bitcoin",
        "asset_type": "crypto",
        "theme": "core",
        "source": "default",
        "enabled": True,
        "order": 10,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 3650)),
    },
    {
        "symbol": "ETHUSD",
        "name": "Ethereum",
        "asset_type": "crypto",
        "theme": "core",
        "source": "default",
        "enabled": True,
        "order": 20,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 3650)),
    },
    {
        "symbol": "SOLUSD",
        "name": "Solana",
        "asset_type": "crypto",
        "theme": "beta",
        "source": "default",
        "enabled": True,
        "order": 25,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 3650)),
    },
    {
        "symbol": "DOGEUSD",
        "name": "Dogecoin",
        "asset_type": "crypto",
        "theme": "beta",
        "source": "default",
        "enabled": True,
        "order": 27,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 3650)),
    },
    {
        "symbol": "ETHBTC",
        "name": "Ethereum / Bitcoin",
        "asset_type": "crypto",
        "theme": "relative-strength",
        "source": "default",
        "enabled": True,
        "order": 28,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 3650)),
    },
    {
        "symbol": "FETUSD",
        "name": "Fetch.ai",
        "asset_type": "crypto",
        "theme": "ai",
        "source": "default",
        "enabled": True,
        "order": 30,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "RENDERUSD",
        "name": "Render",
        "asset_type": "crypto",
        "theme": "ai",
        "source": "default",
        "enabled": True,
        "order": 40,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "TAOUSD",
        "name": "Bittensor",
        "asset_type": "crypto",
        "theme": "ai",
        "source": "default",
        "enabled": True,
        "order": 50,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "AKTUSD",
        "name": "Akash Network",
        "asset_type": "crypto",
        "theme": "ai",
        "source": "default",
        "enabled": True,
        "order": 60,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "EURUSD",
        "name": "Euro / US Dollar",
        "asset_type": "forex",
        "theme": "fx",
        "source": "default",
        "enabled": True,
        "order": 70,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "DXY",
        "name": "US Dollar Index",
        "asset_type": "index",
        "theme": "fx",
        "source": "default",
        "enabled": True,
        "order": 80,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "DJI",
        "name": "Dow Jones Industrial Average",
        "asset_type": "index",
        "theme": "macro",
        "source": "default",
        "enabled": True,
        "order": 85,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "GSPC",
        "name": "S&P 500",
        "asset_type": "index",
        "theme": "macro",
        "source": "default",
        "enabled": True,
        "order": 86,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "NDX",
        "name": "Nasdaq 100",
        "asset_type": "index",
        "theme": "macro",
        "source": "default",
        "enabled": True,
        "order": 87,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "VIX",
        "name": "CBOE Volatility Index",
        "asset_type": "index",
        "theme": "volatility",
        "source": "default",
        "enabled": True,
        "order": 88,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "TNX",
        "name": "US 10Y Treasury Yield",
        "asset_type": "index",
        "theme": "rates",
        "source": "default",
        "enabled": True,
        "order": 89,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "USDRUB",
        "name": "US Dollar / Russian Ruble",
        "asset_type": "forex",
        "theme": "fx",
        "source": "default",
        "enabled": True,
        "order": 90,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "USDCNY",
        "name": "US Dollar / Chinese Yuan",
        "asset_type": "forex",
        "theme": "fx",
        "source": "default",
        "enabled": True,
        "order": 100,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "IMOEX",
        "name": "MOEX Russia Index",
        "asset_type": "index",
        "theme": "russia",
        "source": "moex",
        "enabled": True,
        "order": 102,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "RTSI",
        "name": "RTS Index",
        "asset_type": "index",
        "theme": "russia",
        "source": "moex",
        "enabled": True,
        "order": 104,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "GDAXI",
        "name": "DAX 40",
        "asset_type": "index",
        "theme": "europe",
        "source": "default",
        "enabled": True,
        "order": 106,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "STOXX50E",
        "name": "Euro Stoxx 50",
        "asset_type": "index",
        "theme": "europe",
        "source": "default",
        "enabled": True,
        "order": 108,
        "candles": _candles(("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "XAUUSD",
        "name": "Gold",
        "asset_type": "metal",
        "theme": "hard-assets",
        "source": "default",
        "enabled": True,
        "order": 110,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "XAGUSD",
        "name": "Silver",
        "asset_type": "metal",
        "theme": "hard-assets",
        "source": "default",
        "enabled": True,
        "order": 120,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "NATGASUSD",
        "name": "Natural Gas",
        "asset_type": "energy",
        "theme": "energy",
        "source": "default",
        "enabled": True,
        "order": 130,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "BRENTUSD",
        "name": "Brent Crude",
        "asset_type": "energy",
        "theme": "energy",
        "source": "default",
        "enabled": True,
        "order": 140,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "WTIUSD",
        "name": "WTI Crude",
        "asset_type": "energy",
        "theme": "energy",
        "source": "default",
        "enabled": True,
        "order": 150,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
    {
        "symbol": "URALSUSD",
        "name": "Urals Crude",
        "asset_type": "energy",
        "theme": "energy",
        "source": "default",
        "enabled": False,
        "order": 160,
        "candles": _candles(("15m", 5760), ("1h", 8760), ("4h", 4380), ("1d", 1095)),
    },
]
