from __future__ import annotations

from src.apps.news.contracts import (
    NewsItemLinkRead,
    NewsItemRead,
    NewsPluginRead,
    NewsSourceCreate,
    NewsSourceRead,
    NewsSourceUpdate,
    TelegramBulkSubscribeRead,
    TelegramBulkSubscribeRequest,
    TelegramDialogRead,
    TelegramDialogSelection,
    TelegramDialogsRequest,
    TelegramDialogSubscribeResult,
    TelegramSessionCodeRequest,
    TelegramSessionCodeRequestRead,
    TelegramSessionConfirmRead,
    TelegramSessionConfirmRequest,
    TelegramSourceFromDialogCreate,
    TelegramWizardFieldRead,
    TelegramWizardRead,
    TelegramWizardStepRead,
)

__all__ = [
    "NewsItemLinkRead",
    "NewsItemRead",
    "NewsPluginRead",
    "NewsSourceCreate",
    "NewsSourceRead",
    "NewsSourceUpdate",
    "TelegramBulkSubscribeRead",
    "TelegramBulkSubscribeRequest",
    "TelegramDialogRead",
    "TelegramDialogSelection",
    "TelegramDialogSubscribeResult",
    "TelegramDialogsRequest",
    "TelegramSessionCodeRequest",
    "TelegramSessionCodeRequestRead",
    "TelegramSessionConfirmRead",
    "TelegramSessionConfirmRequest",
    "TelegramSourceFromDialogCreate",
    "TelegramWizardFieldRead",
    "TelegramWizardRead",
    "TelegramWizardStepRead",
]
