from src.core.errors.catalog import PLATFORM_ERROR_REGISTRY
from src.core.errors.exceptions import (
    AuthenticationFailedError,
    AuthorizationDeniedError,
    ConcurrencyConflictError,
    ControlModeRequiredError,
    ControlTokenInvalidError,
    DuplicateRequestError,
    IntegrationUnreachableError,
    InvalidAccessModeError,
    InvalidStateTransitionError,
    PlatformError,
    PolicyDeniedError,
    PromptVeilLockedPlatformError,
    ResourceNotFoundError,
    ValidationFailedError,
)
from src.core.errors.registry import (
    DuplicateErrorCodeError,
    DuplicateMessageKeyError,
    ErrorDefinition,
    ErrorRegistry,
    ErrorRegistryError,
    UnknownErrorCodeError,
    UnknownMessageKeyError,
)
from src.core.errors.taxonomy import ErrorCategory, ErrorDomain, ErrorSeverity

__all__ = [
    "PLATFORM_ERROR_REGISTRY",
    "AuthenticationFailedError",
    "AuthorizationDeniedError",
    "ConcurrencyConflictError",
    "ControlModeRequiredError",
    "ControlTokenInvalidError",
    "DuplicateErrorCodeError",
    "DuplicateMessageKeyError",
    "DuplicateRequestError",
    "ErrorCategory",
    "ErrorDefinition",
    "ErrorDomain",
    "ErrorRegistry",
    "ErrorRegistryError",
    "ErrorSeverity",
    "IntegrationUnreachableError",
    "InvalidAccessModeError",
    "InvalidStateTransitionError",
    "PlatformError",
    "PolicyDeniedError",
    "PromptVeilLockedPlatformError",
    "ResourceNotFoundError",
    "UnknownErrorCodeError",
    "UnknownMessageKeyError",
    "ValidationFailedError",
]
