MARKET_STRUCTURE_PLUGIN_BINANCE_USDM = "binance_usdm"
MARKET_STRUCTURE_PLUGIN_BYBIT_DERIVATIVES = "bybit_derivatives"
MARKET_STRUCTURE_PLUGIN_MANUAL_PUSH = "manual_push"

MARKET_STRUCTURE_EVENT_SNAPSHOT_INGESTED = "market_structure_snapshot_ingested"
MARKET_STRUCTURE_EVENT_SOURCE_HEALTH_UPDATED = "market_structure_source_health_updated"
MARKET_STRUCTURE_EVENT_SOURCE_ALERTED = "market_structure_source_alerted"
MARKET_STRUCTURE_EVENT_SOURCE_QUARANTINED = "market_structure_source_quarantined"
MARKET_STRUCTURE_EVENT_SOURCE_DELETED = "market_structure_source_deleted"

MARKET_STRUCTURE_SOURCE_STATUS_ACTIVE = "active"
MARKET_STRUCTURE_SOURCE_STATUS_DISABLED = "disabled"
MARKET_STRUCTURE_SOURCE_STATUS_ERROR = "error"
MARKET_STRUCTURE_SOURCE_STATUS_QUARANTINED = "quarantined"

MARKET_STRUCTURE_HEALTH_STATUS_DISABLED = "disabled"
MARKET_STRUCTURE_HEALTH_STATUS_IDLE = "idle"
MARKET_STRUCTURE_HEALTH_STATUS_HEALTHY = "healthy"
MARKET_STRUCTURE_HEALTH_STATUS_STALE = "stale"
MARKET_STRUCTURE_HEALTH_STATUS_ERROR = "error"
MARKET_STRUCTURE_HEALTH_STATUS_QUARANTINED = "quarantined"

MARKET_STRUCTURE_ALERT_KIND_ERROR = "error"
MARKET_STRUCTURE_ALERT_KIND_STALE = "stale"
MARKET_STRUCTURE_ALERT_KIND_QUARANTINED = "quarantined"

DEFAULT_MARKET_STRUCTURE_POLL_LIMIT = 1
MAX_MARKET_STRUCTURE_POLL_LIMIT = 10
MAX_MARKET_STRUCTURE_INGEST_BATCH_SIZE = 250
DEFAULT_MARKET_STRUCTURE_FAILURE_BACKOFF_BASE_SECONDS = 60
DEFAULT_MARKET_STRUCTURE_FAILURE_BACKOFF_MAX_SECONDS = 1800
DEFAULT_MARKET_STRUCTURE_QUARANTINE_AFTER_FAILURES = 5

DEFAULT_BINANCE_USDM_API_BASE_URL = "https://fapi.binance.com"
DEFAULT_BYBIT_API_BASE_URL = "https://api.bybit.com"

MARKET_STRUCTURE_MANUAL_PROVIDER_LIQSCOPE = "liqscope"
MARKET_STRUCTURE_MANUAL_PROVIDER_LIQUIDATION_WEBHOOK = "liquidation_webhook"
MARKET_STRUCTURE_MANUAL_PROVIDER_DERIVATIVES_WEBHOOK = "derivatives_webhook"
MARKET_STRUCTURE_MANUAL_PROVIDER_COINGLASS = "coinglass"
MARKET_STRUCTURE_MANUAL_PROVIDER_HYBLOCK = "hyblock"
MARKET_STRUCTURE_MANUAL_PROVIDER_COINALYZE = "coinalyze"
MARKET_STRUCTURE_MANUAL_INGEST_MODE_WEBHOOK = "webhook"

MARKET_STRUCTURE_INGEST_TOKEN_HEADER = "X-IRIS-Ingest-Token"  # nosec B105 - protocol header name, not a secret
MARKET_STRUCTURE_INGEST_TOKEN_QUERY_PARAMETER = "token"  # nosec B105 - query parameter name, not a secret
