ANOMALY_TYPE_PRICE_SPIKE = "price_spike"
ANOMALY_TYPE_VOLUME_SPIKE = "volume_spike"
ANOMALY_TYPE_VOLATILITY_REGIME_BREAK = "volatility_regime_break"
ANOMALY_TYPE_RELATIVE_DIVERGENCE = "relative_divergence"
ANOMALY_TYPE_CROSS_ASSET_SYNCHRONOUS_MOVE = "cross_asset_synchronous_move"
ANOMALY_TYPE_FAILED_BREAKOUT = "failed_breakout"
ANOMALY_TYPE_COMPRESSION_EXPANSION = "compression_expansion"
ANOMALY_TYPE_PRICE_VOLUME_DIVERGENCE = "price_volume_divergence"
ANOMALY_TYPE_CORRELATION_BREAKDOWN = "correlation_breakdown"
ANOMALY_TYPE_FUNDING_OPEN_INTEREST_ANOMALY = "funding_open_interest_anomaly"
ANOMALY_TYPE_CROSS_EXCHANGE_DISLOCATION = "cross_exchange_dislocation"
ANOMALY_TYPE_LIQUIDATION_CASCADE = "liquidation_cascade"

ANOMALY_STATUS_NEW = "new"
ANOMALY_STATUS_ACTIVE = "active"
ANOMALY_STATUS_COOLING = "cooling"
ANOMALY_STATUS_RESOLVED = "resolved"
OPEN_ANOMALY_STATUSES = (
    ANOMALY_STATUS_NEW,
    ANOMALY_STATUS_ACTIVE,
    ANOMALY_STATUS_COOLING,
)

ANOMALY_SCOPE_ASSET = "asset"
ANOMALY_SCOPE_SECTOR = "sector"

ANOMALY_EVENT_TYPE = "anomaly_detected"
ANOMALY_SOURCE_FAST_PATH = "fast_path"
ANOMALY_SOURCE_SECTOR_SCAN = "sector_scan"
ANOMALY_SOURCE_MARKET_STRUCTURE_SCAN = "market_structure_scan"
ANOMALY_SOURCE_ENRICHMENT = "enrichment"

FAST_PATH_LOOKBACK = 96
SECTOR_SCAN_LOOKBACK = 72
MARKET_STRUCTURE_LOOKBACK = 72
MIN_DETECTION_CANDLES = 24
MAX_SECTOR_PEERS = 8
MAX_RELATED_PEERS = 5
BENCHMARK_SYMBOL_PREFIXES = ("BTCUSD", "BTCUSDT")
PORTFOLIO_OPEN_POSITION_STATUS = "open"

DETECTOR_WEIGHTS: dict[str, float] = {
    "price": 0.32,
    "volume": 0.18,
    "volatility": 0.20,
    "relative": 0.18,
    "synchronicity": 0.12,
    "derivatives": 0.18,
    "liquidity": 0.16,
}

ENTRY_THRESHOLDS: dict[str, float] = {
    ANOMALY_TYPE_PRICE_SPIKE: 0.56,
    ANOMALY_TYPE_VOLUME_SPIKE: 0.52,
    ANOMALY_TYPE_VOLATILITY_REGIME_BREAK: 0.58,
    ANOMALY_TYPE_RELATIVE_DIVERGENCE: 0.54,
    ANOMALY_TYPE_CROSS_ASSET_SYNCHRONOUS_MOVE: 0.60,
    ANOMALY_TYPE_FAILED_BREAKOUT: 0.55,
    ANOMALY_TYPE_COMPRESSION_EXPANSION: 0.57,
    ANOMALY_TYPE_PRICE_VOLUME_DIVERGENCE: 0.53,
    ANOMALY_TYPE_CORRELATION_BREAKDOWN: 0.56,
    ANOMALY_TYPE_FUNDING_OPEN_INTEREST_ANOMALY: 0.59,
    ANOMALY_TYPE_CROSS_EXCHANGE_DISLOCATION: 0.58,
    ANOMALY_TYPE_LIQUIDATION_CASCADE: 0.62,
}

EXIT_THRESHOLDS: dict[str, float] = {
    ANOMALY_TYPE_PRICE_SPIKE: 0.34,
    ANOMALY_TYPE_VOLUME_SPIKE: 0.30,
    ANOMALY_TYPE_VOLATILITY_REGIME_BREAK: 0.36,
    ANOMALY_TYPE_RELATIVE_DIVERGENCE: 0.32,
    ANOMALY_TYPE_CROSS_ASSET_SYNCHRONOUS_MOVE: 0.38,
    ANOMALY_TYPE_FAILED_BREAKOUT: 0.33,
    ANOMALY_TYPE_COMPRESSION_EXPANSION: 0.34,
    ANOMALY_TYPE_PRICE_VOLUME_DIVERGENCE: 0.31,
    ANOMALY_TYPE_CORRELATION_BREAKDOWN: 0.34,
    ANOMALY_TYPE_FUNDING_OPEN_INTEREST_ANOMALY: 0.37,
    ANOMALY_TYPE_CROSS_EXCHANGE_DISLOCATION: 0.36,
    ANOMALY_TYPE_LIQUIDATION_CASCADE: 0.40,
}

COOLDOWN_MINUTES: dict[str, int] = {
    ANOMALY_TYPE_PRICE_SPIKE: 45,
    ANOMALY_TYPE_VOLUME_SPIKE: 45,
    ANOMALY_TYPE_VOLATILITY_REGIME_BREAK: 90,
    ANOMALY_TYPE_RELATIVE_DIVERGENCE: 60,
    ANOMALY_TYPE_CROSS_ASSET_SYNCHRONOUS_MOVE: 120,
    ANOMALY_TYPE_FAILED_BREAKOUT: 45,
    ANOMALY_TYPE_COMPRESSION_EXPANSION: 60,
    ANOMALY_TYPE_PRICE_VOLUME_DIVERGENCE: 45,
    ANOMALY_TYPE_CORRELATION_BREAKDOWN: 75,
    ANOMALY_TYPE_FUNDING_OPEN_INTEREST_ANOMALY: 90,
    ANOMALY_TYPE_CROSS_EXCHANGE_DISLOCATION: 60,
    ANOMALY_TYPE_LIQUIDATION_CASCADE: 120,
}

REGIME_ENTRY_MULTIPLIER: dict[str | None, float] = {
    None: 1.0,
    "bull_trend": 1.0,
    "bear_trend": 1.05,
    "sideways_range": 1.0,
    "high_volatility": 1.18,
}

SEVERITY_BANDS: tuple[tuple[str, float], ...] = (
    ("critical", 0.85),
    ("high", 0.70),
    ("medium", 0.40),
    ("low", 0.0),
)
